Expand upload action into shell commands

diff --git a/.github/workflows/reltest.yml b/.github/workflows/reltest.yml
--- a/.github/workflows/reltest.yml
+++ b/.github/workflows/reltest.yml
@@ -61,11 +61,51 @@ jobs:
         run: |
            create-dmg ./build/export/BTrain.app \
               --no-version-in-filename \
-              --overwrite ./
+              ./build/export/
 
       - name: Upload the artifacts
-        uses: skx/github-action-publish-binaries@master
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-           args: '*.dmg'
+        run: |
+           AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
+           RELEASE_ID=$"{{ github.ref_name }}"
+           FILE="./build/export/*.dmg"
+           FILENAME=$( basename "${FILE}" )
+           UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
+           echo "Upload URL is ${UPLOAD_URL}"
+
+           # Upload the artifact & capture HTTP response-code in output file.
+           tmp=$(mktemp)
+           response=$(curl \
+              -sSL \
+              -XPOST \
+              -H "${AUTH_HEADER}" \
+              --upload-file "${FILE}" \
+              --header "Content-Type:application/octet-stream" \
+              --write-out "%{http_code}" \
+              --output $tmp \
+              "${UPLOAD_URL}")
+
+           if [ "$?" -ne 0 ]; then
+              echo "**********************************"
+              echo " curl command did not return zero."
+              echo " Aborting"
+              echo "**********************************"
+              cat $tmp
+              rm $tmp
+              exit 1
+           fi
+
+           # If upload is not successful, we must abort
+           if [ $response -ge 400 ]; then
+              echo "***************************"
+              echo " upload was not successful."
+              echo " Aborting"
+              echo " HTTP status is $response"
+              echo "**********************************"
+              cat $tmp
+              rm $tmp
+              exit 1
+           fi
+           cat $tmp | jq
+           rm $tmp
